### ISSUE TITLE
[BUG] 성적인증 이미지 안올라감

### ISSUE THREAD

**Issue by seulnan** [kimleeoh/Back#13]
연서가 그 보내준 코드복붙했는데 
`User info from Redis: { Rscore: '6703e0aff4e66d047e84e65d', _id: '6703e0aff4e66d047e84e65e' }
credit [ false, false ]
[
  {
    fieldname: 'img',
    originalname: '0.jpg',
    encoding: '7bit',
    mimetype: 'image/jpeg',
    destination: 'uploads/',
    filename: 'f9b3955a0455b290739b222a8e23dee5',
    path: 'uploads/f9b3955a0455b290739b222a8e23dee5',
    size: 814816
  }
] undefined`
이런오류 떴습니다 
관리자서버에 인증으로 보내야합니다!

**Comment by daeGULLL** [comment]
해결
